version = 0.1

[default.deploy.parameters]
stack_name = "ri-sightseeing-backend"
resolve_s3 = true
s3_prefix = "ri-sightseeing-backend"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
disable_rollback = true
